let aliases = {
	'screenshot': 'скрин(шот)?',
	'photoshop': 'фотошоп|фш',
	'art': 'арт|рисун(ок|ки)',
	'gif': 'гиф(ка)?',
	'web': 'веб|интернет[ы]?',
	'map': 'карта',
	
	'minecraft': 'майн(крафт)?',
	'rncr': 'рнкр',
	'randomcraft': 'рандомкрафт|рандом|рк',
	'chaoscraft': 'хаоскрафт',
	'likobsk': 'лайкобск',
	'castit': 'кастит',
	'zombiesland': 'зомби[сз]?ленд|зл',
	'nether': 'нижниймир|незз?ер|ад',
	
	'spawn': 'спа[ву]н',
	'oldspawn': 'олдспа[ву]н',
	'hub': 'хаб',
	'whitelist': 'вайт(лист)?',
	'survival': 'выжива(ние|ч)',
	'creative': '[кс]реат(ив)?',
	'parkour': 'паркур|par[kc]o?ur',
	'skyblock': 'скайблок|сб',
	'skywars': 'скайв[ао]рс|св',
	'bedwars': 'б[еэ]дв[ао]рс|бв',
	'castlewars': 'каст?лв[ао]рс|кв',
	'skygrid': 'скайгрид',
	'build': 'билд(-?сервер)?',
	'hungergames': '(голодные|хангер)-?(игры|геймс)|хг',
	'survivalgames': 'с[ую]рв(ай|и)вал-?геймс|сг',
	'minigames': 'мини(игры|геймс)|мг',
	'prophunt': 'прятки|пропхант',
	'spleef': 'сплиф',
	'kingdoms': 'кингдомс?|королевства',
	
	'getup': '(г|дж)[еэиы]т[ау]п|getup1(new)?',
	'haivon': 'хайвон',
	'playerchar': 'пл[аое]й?ер(-?чар)?|чар(уш(ка|ек)?)?|player(-?char)?|char',
	'dragon': 'др[аэ][кг]он(2488)?|ар[чх](ен[гж]иус)?|(антик(ь?ю|у)и)?авиум',
	'rult': 'р[ау]л[еь]?т',
	'laimon': 'лаймон',
	'likob': 'л(ай|и)коб|лик',
	'imody': '(и|ай)моди',
	'kamka': 'камка(-?ассасс?ин)',
	'namiya': 'намия',
	'himlin': 'хим(лин)?',
	'rutschi': 'рут(с?чи)?',
	'metasux': 'мета(сакс)?',
	'munogun': 'мун(ог[ау]н|я)',
	'delwex': 'д(ел|оль)векс',
	'cubbins': 'к[ау]бб?инс|кабб?(ина)?',
	'subsub': 'с[ау]б(с[ау]б)?',
	'columb': '[зск][ао]лум[бп]',
	'vasya': 'вася(ок)?',
	'paper': 'п(а|эй|ей)пер|бума(г|жк)а',
	'googlecrasher': '(гугл[о-]?)?крашер',
	'snipercom': 'сн(ай|и)пер(-?ком)?',
	'dreggman': '(доктор|др)?эгг?ман',
	'nekobot': 'некобот',
	'ezmac': '[эе]змак',
	'fabi': 'фаби(о?ус)?',
	'romkago': 'ромка(го)?',
	'bladbl': 'бладбл',
	'anderkf': 'андеркф',
	'raven': 'равен',
	'danchi': 'данчи',
	'krabik': 'крабик',
	'dar1kooo': 'дарико*',
	'admiralmanul': '(адмирал-?)?манул',
	'nano': 'нано(-?человек)?|nano(-?(4|ch)elovek)?',
	'3iluminati': '(3?и|три)лл?юм(инати)?',
	'iiokep': '(([ч4]?п|ии)о|чоч)кер|((ch|4)?po|4[0o]4)ke[rp]',
	'mrdeed': 'deed|(мр)?д[еи]д',
	'desalis': 'д[еи]салис',
	
	'sign': 'табличка',
	'cake': 'торт(ик)?',
	'creeper': 'крип(ер|ак)',
	'villager': 'житель',
	'irondoor': 'железнаядверь|жд',
	'launcher': 'лаунчер',
	'aor': 'аор',
	'sdf': 'сдф',
	
	'bug': 'баг',
	'rip': 'рип',
	'dank': 'д[аэ]нк',
	'event': '[эи]вент',
	'aprilfools': '(1|первое-?)апреля',
	'overview': 'обзор',
}

// turn text into regular expressions
for (tag in aliases) {
	let text = aliases[tag]
	aliases[tag] = new RegExp('^(' + text + ')$', 'i')
}

// server-side use
if (typeof window == 'undefined') {
	module.exports = aliases
}